//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercy_Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> Categorie { get; set; }
        public string Detalies { get; set; }
        public string IBAN { get; set; }
        public string ALICI_PTT_HESAP_NO { get; set; }
        public string ALICI_PTT_MUSTERI_NO { get; set; }
    
        public virtual Categoire Categoire { get; set; }
    }
}
