//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercy_Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Employee_Details
    {
        public int ID { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public byte[] Time_Sheet { get; set; }
        public byte[] Signature { get; set; }
        public byte[] Contract { get; set; }
    
        public virtual TB_Employee TB_Employee { get; set; }
    }
}
