//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercy_Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Employee()
        {
            this.TB_Employee_Details = new HashSet<TB_Employee_Details>();
        }
    
        public int ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Name_Ar { get; set; }
        public string Emp_Phone { get; set; }
        public string Emp_Email { get; set; }
        public Nullable<int> Emp_Zoho { get; set; }
        public string Emp_State { get; set; }
        public Nullable<int> ID_cat { get; set; }
        public string ALICI_PTT_HESAP_NO { get; set; }
        public string ALICI_PTT_MUSTERI_NO { get; set; }
    
        public virtual Categoire Categoire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Employee_Details> TB_Employee_Details { get; set; }
    }
}
