//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercy_Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Payment_Request
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Project_Name { get; set; }
        public string Funded_By { get; set; }
        public string PR_NO { get; set; }
        public string Budget_line { get; set; }
        public string Type { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Reference_Number { get; set; }
        public string Payment_method { get; set; }
        public string Transfer_to { get; set; }
        public string PTT_Bank_Info { get; set; }
        public string MUSTERI_NO { get; set; }
        public string IBAN { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Notes { get; set; }
        public string Link_for_details { get; set; }
        public string Reporting { get; set; }
        public string Add_By { get; set; }
    }
}
