//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercy_Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Project
    {
        public int ID { get; set; }
        public string Pro_Name { get; set; }
        public string Pro_Des { get; set; }
        public Nullable<System.DateTime> Pro_Date_Start { get; set; }
        public Nullable<System.DateTime> Pro_Date_End { get; set; }
        public string Pro_URL { get; set; }
    }
}
