//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercy_Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Salary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Salary()
        {
            this.TB_Monthly_Report = new HashSet<TB_Monthly_Report>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Zoho { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<double> Gross { get; set; }
        public Nullable<double> Other_additions { get; set; }
        public Nullable<double> Transportation { get; set; }
        public Nullable<double> Other_deduction { get; set; }
        public Nullable<double> Net_Deu { get; set; }
        public string Project { get; set; }
        public string Payroll { get; set; }
        public string For_manth { get; set; }
        public Nullable<System.DateTime> Preparation_date { get; set; }
        public string Currency { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Monthly_Report> TB_Monthly_Report { get; set; }
    }
}
